FROM docker.io/automaticmode/active_workflow:0.9.15.1

# Remove after the release
COPY docker/scripts/entrypoint-heroku /app/docker/scripts/

# Use custom entrypoint as heroku doesn't run docker with root privileges.
ENTRYPOINT ["/app/docker/scripts/entrypoint-heroku"]
