#!/bin/bash
set -e

cat > /etc/dpkg/dpkg.cfg.d/01_nodoc <<EOF
# Delete locales
path-exclude=/usr/share/locale/*

# Delete man pages
path-exclude=/usr/share/man/*

# Delete docs
path-exclude=/usr/share/doc/*
path-include=/usr/share/doc/*/copyright
EOF

export LC_ALL=C
export DEBIAN_FRONTEND=noninteractive
minimal_apt_get_install='apt-get install -y --no-install-recommends'

apt-get update
$minimal_apt_get_install build-essential git-core \
  zlib1g-dev libyaml-dev libssl-dev libgdbm-dev libreadline-dev \
  libncurses5-dev libffi-dev libxml2-dev libxslt-dev libcurl4-openssl-dev libicu-dev \
  graphviz libgraphviz-dev \
  libpq-dev libsqlite3-dev tzdata \
  postgresql-11 tini

apt-get purge -y python3* rsyslog rsync manpages
apt -y autoremove
apt-get -y clean

rm -rf /var/lib/apt/lists/*
rm -rf /usr/share/doc/
rm -rf /usr/share/man/
rm -rf /usr/share/locale/
rm -rf /var/log/*

useradd --home-dir /app --no-create-home --no-log-init active_workflow
mkdir -p /app
chown -R active_workflow /app
chmod 700 /app
