#!/bin/bash
set -e

export LC_ALL=en_US.UTF-8

cd /app

export HOME=/app
if ! whoami &> /dev/null; then
    if [ -w /etc/passwd ]; then
        echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
    fi
fi

mkdir -p tmp/pids tmp/cache tmp/sockets log
